### ISSUE TITLE
Script breaks if not all scans are available

### ISSUE THREAD

**Issue by heilands** [audius/audiness#6]
If a history is given which is not present for all scans (because the scan was started some months later or is deleted) the script stops running with the error message:
_"Scan not available"_

Error handling would be nice, so that all available scan of the given period are downloaded.

**Comment by fabaff** [comment]
At first glance I would say that it would be possible to run through the whole selection by skipping the missing historical scans.

Not sure, how missing scans could be spotted after exporting them, though.

**Comment by heilands** [comment]
Skipping scans will be fine. Yes, search for missing scans would be a manual task then. But nevertheless, it would be even more automated then manual downloading.

Another idea: Maybe scan name for the missing scans could be exported to a list and shown at the end. But that would be additional.
